project:
  type: website
  resources:
    - keybase.txt
    - resume.pdf

website:
  title: "Isa AlDoseri"
  site-url: https://isados.github.io/blog/
  site-path: https://isados.github.io/blog/
  description: "A Fun Tomorrow"
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: isados/blog
  navbar:
    background: "#192bc2"
    right:
      - text: "Blog"
        href: blog.html
      - text: "Experience"
        href: CV.html
      - text: Awards
        href: awards.html
      - text: "Papers"
        href: papers
      - icon: github
        url: https://github.com/isados/blog
      - icon: rss
        href: blog.xml
  page-footer:
    center: "Â© Copyright 2023 Isa AlDoseri. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."
format:
  html:
    theme:
      light: [cosmo, custom.scss]
      # dark: [darkly, _variables.scss]
    # css: styles.css
    highlight-style: eiffel
    smooth-scroll: true

    # mainfont: "Atkinson Hyperlegible"
